default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'dev' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'prod' %>
